version: '3.8'

volumes:
  db-data:
  
services:
  web:
    container_name: rails
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/rails_product-in'
    environment:
      - 'DATABASE_PASSWORD=postgres'
    # -itの部分↓
    tty: true
    stdin_open: true
    depends_on:
      - db

  db:
    container_name: postgres_db
    image: postgres
    environment:
    - 'POSTGRES_USER=postgres'
    - 'POSTGRES_PASSWORD=postgres'
    # テスト環境で使用↓
    - 'POSTGRES_HOST_AUTH_METHOD=trust'
    volumes:
      - 'db-data:/var/lib/postgresql/data'